### ISSUE TITLE
TypeScript compilation error

### ISSUE THREAD

**Issue by hactrz** [isprojects/mstform#35]
```
const Profile = types.model('Profile', {
    first_name: types.maybeNull(types.string),
})

const form = new Form(Profile as any, {
    first_name: new Field(converters.maybe(converters.string))
})

const formState = form.state(clone(this.props.profile))

const first_name = this.formState.field('first_name')
```
ERROR: TS2345: Argument of type '"first_name"' is not assignable to parameter of type 'never'

**Comment by faassen** [comment]
Hm, I'm not sure what happens with this.props.profile. I assume it's an instance of Profile.

Could you supply a self-contained example that demonstrate this error? It's possible it's a MST 3 incompatibility, as I see you use types.maybeNull(). But 'Profile as any' is the biggest red flag: MSTForm uses the type information on Profile to verify whether you can access the field first_name, but you strip away that type information there. There must be a reason why you'd do that, and THAT may again be due to MST 3 incompatibility.

**Comment by faassen** [comment]
MST 3 support is now merged, so closing this.
